pipeline {
   agent {
        node {
            label 'AGENT-1'
        }
    }
    environment {
        appVersion = ''
        REGION = "us-east-1"
        ACC_ID = "784585544641"
        PROJECT = "roboshop"

    }
    options {
        timeout(time: 30, unit: 'MINUTES') 
        disableConcurrentBuilds()
          ansiColor('xterm')
    }
     /*  parameters {
        string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
        text(name: 'BIOGRAPHY', defaultValue: '', description: 'Enter some information about the person')
        booleanParam(name: 'TOGGLE', defaultValue: true, description: 'Toggle this value')
        choice(name: 'CHOICE', choices: ['One', 'Two', 'Three'], description: 'Pick something')
        password(name: 'PASSWORD', defaultValue: 'SECRET', description: 'Enter a password') 
    } */
// build
    stages {
        stage('init') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1'){
                         sh """  
                            cd 10-sg/
                            terraform init -reconfigure
                     """
                    }
                }
            }
        }
    
        stage('plan') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1'){
                         sh """  
                            cd 10-sg
                            terraform plan
                         """
                    }
                }
            }
        }
       stage('apply') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                        sh """
                           cd 10-sg
                            terraform apply -auto-approve
                        """
                    }
                }
            }
        }
        stage('Bastion acm eks') {
            parallel {
                stage('Trigger Bastion') {
                    steps {
                        script {
                            build job: '20-bastion',
                            wait: false, // vpc will not wait for sg pipeline completion
                            propagate: false // even sg fails vpc will not be affected
                        }       
                    }
                } 
                stage('Trigger eks') {
                    steps {
                        script {
                            build job: '80-eks',
                            wait: false, // vpc will not wait for sg pipeline completion
                            propagate: false // even sg fails vpc will not be affected
                        }       
                    }
                }
                stage('acm alb') {
                    stages{
                        stage('Trigger acm') {
                            steps {
                                script {
                                    build job: '60-acm',
                                    wait: false, // vpc will not wait for sg pipeline completion
                                    propagate: false // even sg fails vpc will not be affected
                                }       
                            }
                        }
                        stage('Trigger alb') {
                            steps {
                                script {
                                    build job: '70-frontend-alb',
                                    wait: false, // vpc will not wait for sg pipeline completion
                                    propagate: false // even sg fails vpc will not be affected
                                }       
                            }
                        }
                    }
                }
            }
        }
    }

               
       


    post { 
        always { 
            echo 'I will always say Hello again!'
        }
        success {
            echo 'hi this is success'
            deleteDir()
        }
        failure {
            echo 'hi, this is failure'
        }
    }
}



    